### ISSUE TITLE
"Help" menu item should launch the browser with a predefined URL

### ISSUE THREAD

**Issue by nbhasker** [CAGoodman/CareWheelsCorp#23]
Help documentation will be web-based

**Comment by nbhasker** [comment]
We will use http://carewheels.org/carebank/help  as the URL for help.

**Comment by nbhasker** [comment]
Per latest from Claude - the help URL will be https://sites.google.com/a/carewheels.com/carebank/

**Comment by agvardha** [comment]
Error Message:
8100/#/app/groupStatus:1 XMLHttpRequest cannot load https://sites.google.com/a/carewheels.com/carebank/. Redirect from 'https://sites.google.com/a/carewheels.com/carebank/' to 'https://www.google.com/a/UniversalLogin?service=jotspot&passive=1209600&continue=https://sites.google.com/a/carewheels.com/carebank/&followup=https://sites.google.com/a/carewheels.com/carebank/&md=carewheels.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

Bhasker please check this for more info:
https://stackoverflow.com/questions/31779599/angular-how-to-work-with-https-using-http

CORS has to be enabled on the server side to call https call using $https

**Comment by agvardha** [comment]
With this fix 
window.open("https://sites.google.com/a/carewheels.com/carebank/");
Provided by Bhasker it worked perfect both on ionic serve and Galaxy mobile
