### ISSUE TITLE
Data is stale on bringing app back to the foreground

### ISSUE THREAD

**Issue by nbhasker** [CAGoodman/CareWheelsCorp#31]
If the app is in the background for an extended period, such as overnight it is likely that the data is stale as the periodic refresh would likely not have been scheduled for some time. On an automatic re-login if the application has lost its resources, we refresh the data. We should probably do the same thing on a normal resume if a refresh hasn't happened for some time. The app will have to remember the time of the last refresh and force a refresh if the data is older than some threshold.

**Comment by agvardha** [comment]
Check the comment in app.js near resume

**Comment by agvardha** [comment]
This has been fixed but not verified
