### ISSUE TITLE
Swipe to reveal side menu generally doesn't work

### ISSUE THREAD

**Issue by nbhasker** [CAGoodman/CareWheelsCorp#33]
It only works on the Group Status screen. It doesn't work on the many other views (Individual Status, Reminders, advanced, etc) that show the Menu hamburger button.

**Comment by agvardha** [comment]
I had seen it once in a while but never noted where all it worked systematically. But it is a good point. You put it so succinctly with so many few words but leaving no chance for doubt.  I like it :-)

**Comment by agvardha** [comment]
Duplicate
