### ISSUE TITLE
Auto-login from background fails sometime

### ISSUE THREAD

**Issue by nbhasker** [CAGoodman/CareWheelsCorp#34]
It's relatively easy to reproduce on a Nexus 7 running Android 6 especially if the  `Developer Options | Don't Keep Activities` option is set.

**Comment by agvardha** [comment]
I have fixed it but will not close the issue till Bill certifies it, I will also do some through testing before closing this.

**Comment by agvardha** [comment]
I could not duplicate it in Samsung Galaxy Note 5 running 7.0 nor on Nexus 5X LGE running Android 7.1.2. I did call Bill and he has a Nexus 5X LGE running Android 7.1.2. He also could not duplicate it. So we have to conclude when ever it was reported the apk had some other issue which manifested as this. So I shall close this issue.

**Comment by nbhasker** [comment]
Made code changes to save parameters in SQLite based persistent storage rather than "local storage" since local storage can be reclaimed by the OS when there is resource stress with the app in the background. Further changed the logic to avoid writing in the pause handler as it appeared that some of those writes weren't allowed to complete.. 

The semantics now cause a auto-login any time there's a session. Logout - now a first class operation - ends the session and presents the login screen as before. This is a change but makes the app more consistent with common practice.

This has eliminated the failures seen on the emulator with the "delete activities" developer option set.

Retaining this on the NBSQLite branch for now as it is primarily intended to solve the IOS issue.

**Comment by nbhasker** [comment]
The SQLite solution has been merged back to Android and release as 1.1.20.
