### ISSUE TITLE
Logout does not really log you out 

### ISSUE THREAD

**Issue by agvardha** [CAGoodman/CareWheelsCorp#37]
This is a major security hole. I think at some point when we implemented logout we knew this and discussed that a "logout" is not like a real logout from a OS or other secure application. We are merely displaying the login view, nothing really is "logged" out. All you have to do is tap the back button you are back fully logged. Even when the creds are not saved it puts you back in. The only way to really keep it logged out is to clear its data cache which is same as kilingl the app thread. 
I did checked of the pause/resume logs and did not see them. So when we hit the back button it is the Android app putting it back. The problem is we cannot the clear the app data cache and then hope to remember creds. So we can totally log user out but then remembered creds are lost. So the solution should work for remembered and non-remembered creds.

**Comment by nbhasker** [comment]
Just add    ` $ionicHistory.clearHistory();` at the beginning of the login controller (just as we do for the Group Status view). This will ensure that the Android back button has no effect.

Another additional safety will be to clear `user.username` and `user.password` or the whole `user` structure in `userService.js/logout()`.

**Comment by agvardha** [comment]
added $ionicHistory.clearHistory(); adn it is fixed,  Fixed and verified
