### ISSUE TITLE
Login header does not specify processor type

### ISSUE THREAD

**Issue by agvardha** [CAGoodman/CareWheelsCorp#40]
Just looking at the log file one cannot say what was the processor armv7 or x86. Need to add this to log header.

**Comment by nbhasker** [comment]
Technically you can. The Version will end with a 2 for ARMv7 systems and a 4 for x86 systems. It appears that someone is using an x86 Asus Zenphone (ASUS_T00J) and you can see the version code (now called build number) is 101134 for Version 1.1.13. In the normal ARMv7 case, the version code would be 101132.

**Comment by agvardha** [comment]
Yes I was using ASUS so this is not a issue any more.  I shall remember this. Thanks
