### ISSUE TITLE
Balance and related amount should display to 2 decimal places

### ISSUE THREAD

**Issue by agvardha** [CAGoodman/CareWheelsCorp#44]
When it read 72.6 it means 72.60 however when it says 0.1 it does not mean 0.10 :-). So our disaplay should always uniformally  display 2 decimal places.

**Comment by nbhasker** [comment]
Our credist are in units of T$0.1 so there can never be more than one decimal place in normal usage.

**Comment by nbhasker** [comment]
Is this still an issue or can we close it?
