### ISSUE TITLE
Resetting balance to 0 does not work

### ISSUE THREAD

**Issue by agvardha** [CAGoodman/CareWheelsCorp#45]
I had 0.2 in my balance. Logged in as Admin and did the "Payment as user to system" --> Debited 0.02 cents.  So I should have 0 balance in my account, CareBank account info says Balance at begin of period:T$0.00 however the display on the mobile still shows as 0.2. Doing a forced refresh also did not help

**Comment by nbhasker** [comment]
Is this still an issue or can we close it?
