### ISSUE TITLE
CareBank account Balance keep bumping does not reflect GS values 

### ISSUE THREAD

**Issue by agvardha** [CAGoodman/CareWheelsCorp#46]
Member Account:
Balance at the begin of period: 0, Current Balance: 0.26 and Balance at end of period: 0.26.Total outflow = 76.74 and total income: 77. The GS display shows the balance as 0.3 --> First bug that they dont match
Then did a debit payment of 0.26 and made the balance to 0. I did a refresh on my mobile and it also became 0. After 5 min the mobile changed to 0.1 and CareBank changed to 0.10!! Then I did IS, GS and a refresh. The balance became 0.3 - mobile and 0.30 - CareBank.  If it is within our power to fix CareBank then we should make it follow norms else in the future it will stump other people too.
On my account I went on accruing credits finally when I crossed T$0.90 it became T$1.0 and mobile phone shows 1.0. Question under what circumstance can we end up with T$0.26? Tomorrow Jeff will have all this questions if he were to validate I just wanted to make it uniform ...

**Comment by nbhasker** [comment]
Please reset the accounts carefully to zero as you start testing. Or take careful note of the starting balances and avoid adjusting the balances manually as there have several typos doing that.

**Comment by nbhasker** [comment]
To answer your questions specifically the only way in which the balance can become T$0.26 is by manual adjustment.

**Comment by nbhasker** [comment]
Is this still an issue or can we close it?

**Comment by nbhasker** [comment]
Need more clarity to understand the issue here
