### ISSUE TITLE
Making Call using ionic serve errors out but payment happens although intermittently 

### ISSUE THREAD

**Issue by agvardha** [CAGoodman/CareWheelsCorp#47]
Bug1: In an ionic serve run, when you tap the Call button the $http() call fails saying bad local network error. 
Bug2: However the server says the payment went through
Bug3: However not all the call is recorded by the server so some of them do miss. Out of 5 calls 3 went through.
When I used the mobile every time it went through and I was using the same network(wifi). There is a cordova call which connects the app to the local call function.  ionic serve does not support cordova and that is the reason it fails. Need more investigation.

**Comment by nbhasker** [comment]
Not sure what this means. Need clarity if we are to retain.

**Comment by agvardha** [comment]
Ionic serve run is not configured to make a phone call. So it fails in that case technically the user who made the call should not get the credit. If the user gets the credit then the person whom he/she called gets debited although the call never went through. We have assume tow process here

**Comment by agvardha** [comment]
![callpayment](https://user-images.githubusercontent.com/23228929/27877869-2b46721a-6171-11e7-95fe-0e19a3e08a57.JPG)

This is a ionic serve run and when I clicked the call nothing happened. http did not error out but you will see : Call payment is true, Claude was debited and Alice credited for a call which never got connected to the phone app. 

alertlevel=red&callpayment=**True**&membersummarypayment=False&sensordataviewpayment=False&username=testalice&usernametocredit=testalice&usernametodebt=CAGoodman"

**Comment by nbhasker** [comment]
I suggest we close this issue or mark as "wontfix". 

This happens when the Cyclos configuration is incomplete (ie. no phone number) and shouldn't apply to normal operation where we will have a phone number.

**Comment by agvardha** [comment]
After much testing between ionic serve, emulator and real device I have come to the conclusion this is very much ionic issue only and not real filed issue. Hence will close this. Bhasker I should have listened to you in the first case and saved some time :-)
