### ISSUE TITLE
Need scrub of all the user visible strings in the app

### ISSUE THREAD

**Issue by nbhasker** [CAGoodman/CareWheelsCorp#58]
Need a full review of all the user visible strings displayed by the app and make sure that they are informative and accurate. For example, the reminder text "Please check in with your CareWheels friendly customer support!" is not correct. Filed as separate issue.

**Comment by agvardha** [comment]
All done and validated, hope have not missed anything. Thanks to Jack for the help. In the future when we add more messages need to ensure to follow the same messages.
